---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  keypair:
    Description: your key pair in us-east-1 region
    Type: String
Resources:
  sle-jumpbox:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-002cc39e7bf021a77
      KeyName: Ref: keypair
      UserData:
        Fn::Base64:
          Fn::Join:
          - "\n"
          - - "#!/bin/bash -xe"
            - yum update -y aws-cfn-bootstrap
            - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            - unzip awscli-bundle.zip
            - sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
